packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.59.0
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.13
  typescript: ^5.6.2
  zod: ^3.23.8

  "@types/node": ^20.16.10
  "@t3-oss/env-nextjs": ^0.11.1
  next: ^14.2.15
  jiti: ^2.3.1
  postcss: ^8.4.47
  "@radix-ui/react-dropdown-menu": ^2.1.2
  react-hook-form: ^7.53.0
  tailwind-merge: ^2.5.3

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.0
